import { createHash } from 'node:crypto';

import type { Plugin } from 'vite';

/**
 * Response headers for a static-assets Worker, written at build time.
 *
 * Cloudflare serves `_headers` from the assets directory, so the policy ships
 * with the build it describes rather than living in a dashboard. It is
 * generated, not hand-written, for one reason: both sites run a small inline
 * script before first paint (the theme, so a dark-mode reader never sees a
 * white flash), and a strict `script-src` has to name that script by its hash.
 * A hash typed by hand goes stale the first time somebody edits the script,
 * and the failure is a site that silently stops honouring the theme.
 */

export type CspDirectives = Record<string, readonly string[]>;

export interface SecurityHeadersOptions {
  /** CSP directives. `script-src` gains the inline scripts' hashes. */
  csp: CspDirectives;
  /** Extra `_headers` blocks appended as written, e.g. cache rules. */
  extra?: string;
}

/** Every inline `<script>` body in a page — those without a `src`. */
function inlineScripts(html: string): string[] {
  const scripts: string[] = [];
  const pattern = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi;

  for (const match of html.matchAll(pattern)) {
    if (match[1] && match[1].trim() !== '') scripts.push(match[1]);
  }

  return scripts;
}

function hashOf(script: string): string {
  return `'sha256-${createHash('sha256').update(script, 'utf8').digest('base64')}'`;
}

function serialise(csp: CspDirectives): string {
  return Object.entries(csp)
    .map(([name, values]) => [name, ...values].join(' ').trim())
    .join('; ');
}

export function securityHeaders(options: SecurityHeadersOptions): Plugin {
  return {
    name: 'noto-security-headers',
    apply: 'build',
    enforce: 'post',

    generateBundle(_output, bundle) {
      const page = bundle['index.html'];
      const html = page && page.type === 'asset' ? String(page.source) : '';

      const csp: CspDirectives = {
        ...options.csp,
        'script-src': [
          ...(options.csp['script-src'] ?? ["'self'"]),
          ...inlineScripts(html).map(hashOf),
        ],
      };

      const source = [
        '# Generated by tooling/vite/security-headers.mts at build time. Do not edit.',
        '',
        '/*',
        `  Content-Security-Policy: ${serialise(csp)}`,
        '  X-Content-Type-Options: nosniff',
        '  X-Frame-Options: DENY',
        '  Referrer-Policy: strict-origin-when-cross-origin',
        '  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=()',
        '  Cross-Origin-Opener-Policy: same-origin',
        '',
        options.extra ?? '',
      ].join('\n');

      this.emitFile({ type: 'asset', fileName: '_headers', source });
    },
  };
}

/**
 * The origin of a configured URL, and its WebSocket twin, for `connect-src`.
 * Empty when the value is missing or not a URL — a build without a cloud has
 * nothing to connect to, and says so by omission.
 */
export function originsOf(...values: (string | undefined)[]): string[] {
  return values.flatMap((value) => {
    if (!value) return [];

    try {
      const origin = new URL(value).origin;
      return [origin, origin.replace(/^http/, 'ws')];
    } catch {
      return [];
    }
  });
}
